### PR TITLE
Reenable more tests

### PR DESCRIPTION
**Pull request by cognifloyd**
Updated the rmq setup role to drop the install script hack. Enabled tests for Ubunutu 20.04 in more places, and reenabled Ubuntu 18.04 + Ansible 2.9.

Adding other  platforms for integration tests doesn't make sense because the roles do not support anything other than Ubuntu.

- :heavy_check_mark: Ubuntu 20.04 in https://github.com/ansible-collections/community.rabbitmq/pull/93/commits/19e60fdca68384f34c1e98ad33b5328ca18b52f2
- :white_check_mark: CentOS 7 in https://github.com/ansible-collections/community.rabbitmq/pull/93/commits/346dc976de3d2ff8923c9b584bd6e5f54690020e _effectively a noop, so reverted in https://github.com/ansible-collections/community.rabbitmq/pull/93/commits/ed6f5ec4d9132c12628241fec9a9cdc5b772a7b1_
- :heavy_check_mark: Ubuntu 18.04 + Ansible 2.9

### CODE REVIEW

**Comment by cognifloyd** [comment]
Hmm. Even if we enable integration tests for non-ubuntu platforms, the tests are essentially noop.
This is because the integration tests all use `setup_rabbitmq` which has one task in `main.yml`:
https://github.com/ansible-collections/community.rabbitmq/blob/346dc976de3d2ff8923c9b584bd6e5f54690020e/tests/integration/targets/setup_rabbitmq/tasks/main.yml#L6-L7

Each of the other roles has a similar task. So, to effectively enable ANY platforms other than ubuntu, we have to refactor the integration test roles.

**Comment by Andersson007** [comment]
@cognifloyd thanks for doing this!

**Comment by cognifloyd** [comment]
Ah ha!
It turns out Ansible 2.9 is using: `quay.io/ansible/ubuntu1804-test-container:1.8.0`
But 2.10 is using: `quay.io/ansible/ubuntu1804-test-container:1.21.0`
The older docker image has an older `libssl1.1` which is unsupported by erlang. Upgrading it fixed it.

**Comment by cognifloyd** [comment]
All checks are back to green. Please review and merge when you get a chance. Thanks!

**Review by Andersson007 — APPROVED** [review]
@cognifloyd thanks!
Looks like a great job to me! Thanks for covering 20.04 and getting rid of the temporary script solution:)

@odyssey4me could you please take a look too?

**Review by odyssey4me — APPROVED** [review]
Excellent, thank you!

**Comment by Andersson007** [comment]
@cognifloyd great job, such things are super valuable for the project's stability, thank you! Any further help will be much appreciated too.
@odyssey4me thanks for reviewing and approving!

**Pull request merged**
