### PR TITLE
Add testing on Ubuntu 20.04

### PR DESCRIPTION
**Pull request by jrosser**
##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by odyssey4me** [comment]
Hmm, looks like this should have worked - I see a similar PR here: https://github.com/ansible/ansible/pull/69161

**Comment by Andersson007** [comment]
Hi @jrosser ! Thanks for the PR! Is it still relevant? Please update or close the PR.
It would be great to have this tested against Ubutnu 20.04 and I'd be happy to review once the PR is ready.

**Comment by Andersson007** [comment]
I think it's not relevant because now Azure pipelines is used and I added Ubuntu 2004 support today with https://github.com/ansible-collections/community.rabbitmq/pull/78.
Anyway thank you for wish to help!
If you want to make CI better, help wanted in https://github.com/ansible-collections/community.rabbitmq/pull/79.

**Comment by jrosser** [comment]
Thanks for sorting this out 👍 and getting more coverage.

**Pull request closed without merging**
