### PR TITLE
Fix CI pipeline

### PR DESCRIPTION
**Pull request by Knalltuete5000**
##### SUMMARY
Fix the url to the rabbitmq signing keys as well
as the links to the rabbitmq repository

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
CI pipeline

##### ADDITIONAL INFORMATION
The links to the signing keys as well to the repository of rabbitmq have changed

### CODE REVIEW

**Comment by Knalltuete5000** [comment]
The installation of rabbitmq, which was the main problem at first, is fixed by the change but the tests somehow fail.

I have only tested locally the smallest set of tests to verify that the installation works.

It seems like the rabbitmq_policy tests fail based on the log but I do not have any clue why

**Comment by Knalltuete5000** [comment]
@Andersson007  I think I have found the reason the pipeline fails.

First of all the urls to the rabbitmq repositories have changed.

Since the newest version of rabbitmq is installed in the pipeline there are some changes since RabbitMq 3.x:
-  the policy tests fail because they used parameters to create a policy have been deprecated in RabbitMq 3.x release (see https://www.rabbitmq.com/docs/3.13/parameters#why-operator-policies-exist) and were removed in RabbitMq 4.0
- the command `await_online_synchronized_mirror` does not exist in the RabbitMq 4 release

There might be more removals in rabbitmq 4 which I have not discovered yet. But I think this might be an issue on its own to tackle the compatibility of the module with RabbitMq version 3.x and version 4

**Comment by Andersson007** [comment]
@Knalltuete5000 thanks a lot for fixing CI! Much appreciated!
- How about commenting the failing tasks in the CI for now so that we have the rest green?
- About tackling the compatibility issues: let's merge this PR and discuss how to handle them in another dedicated issue. What do you think?

**Comment by Knalltuete5000** [comment]
I have comment out the failing test because of the missing command not available in rabbitmq v4. I have executed all other tests local and they seem to work. Lets wait for the pipeline.

The issue with the missing command/the version difference between 3 and 4 should be handled in an other issue

**Comment by Andersson007** [comment]
@Knalltuete5000 thanks a lot for the contribution! Would you like to create the issue?

**Comment by Knalltuete5000** [comment]
@Andersson007  I have created issue #181. Feel free to add any additional information

**Pull request merged**
