### PR TITLE
Release 1.2.0 commit

### LINKED ISSUE #121: Sanity tests failing in community.rabbitmq
##### SUMMARY
We are running sanity tests across every collection included in the Ansible community package (as part of [this issue](https://github.com/ansible-community/community-topics/issues/96)) and found that ``ansible-test sanity --docker`` against community.rabbitmq 1.1.0 fails with ansible-core 2.13.0rc1 in ansible 6.0.0a2.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
n/a

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.0rc1]
```

##### COLLECTION VERSION

```paste below
1.1.0
```

##### STEPS TO REPRODUCE

```yaml
ansible-test sanity --docker
```

##### EXPECTED RESULTS

Tests are either passing or ignored.

##### ACTUAL RESULTS

```paste below
ERROR: Found 3 import issue(s) on python 3.10 which need to be resolved:
ERROR: plugins/modules/rabbitmq_policy.py:86:0: traceback: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
ERROR: plugins/modules/rabbitmq_user.py:125:0: traceback: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
ERROR: plugins/modules/rabbitmq_user_limits.py:80:0: traceback: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
ERROR: Found 3 replace-urlopen issue(s) which need to be resolved:
ERROR: tests/utils/shippable/check_matrix.py:20:25: use `ansible.module_utils.urls.open_url` instead of `urlopen`
ERROR: tests/utils/shippable/check_matrix.py:23:32: use `ansible.module_utils.urls.open_url` instead of `urlopen`
ERROR: tests/utils/shippable/check_matrix.py:50:31: use `ansible.module_utils.urls.open_url` instead of `urlopen`
ERROR: Found 1 shebang issue(s) which need to be resolved:
ERROR: tests/utils/shippable/timing.py:1:1: unexpected non-module shebang: b'#!/usr/bin/env python3.7'
ERROR: Found 1 shellcheck issue(s) which need to be resolved:
ERROR: tests/utils/shippable/shippable.sh:52:10: SC2242: Can only exit with status 0-255. Other data should be written to stdout/stderr.
ERROR: Found 3 validate-modules issue(s) which need to be resolved:
ERROR: plugins/lookup/rabbitmq.py:0:0: invalid-documentation: DOCUMENTATION.author: Invalid author for dictionary value @ data['author']. Got 'John Imison <@Im0>'
ERROR: plugins/lookup/rabbitmq.py:0:0: invalid-documentation: DOCUMENTATION.lookup: extra keys not allowed @ data['lookup']. Got 'rabbitmq'
ERROR: plugins/lookup/rabbitmq.py:0:0: invalid-documentation: DOCUMENTATION.name: required key not provided @ data['name']. Got None
ERROR: The 5 sanity test(s) listed below (out of 43) failed. See error output above for details.
import --python 3.10
replace-urlopen
shebang
shellcheck
validate-modules
ERROR: Command "podman exec ansible-test-controller-XcHYngfd /usr/bin/env ANSIBLE_TEST_CONTENT_ROOT=/root/ansible_collections/community/rabbitmq LC_ALL=en_US.UTF-8 /usr/bin/python3.10 /root/ansible/bin/ansible-test sanity --containers '{}' --skip-test pylint --metadata tests/output/.tmp/metadata-sm6tmnoq.json --truncate 0 --color no --host-path tests/output/.tmp/host-2osh4m9l" returned exit status 1.
```

### PR DESCRIPTION
**Pull request by csmart**
##### SUMMARY

New release for 1.2.0.

Fixes  #121

### CODE REVIEW

**Review by Andersson007 — APPROVED** [review]
@csmart thanks for the PR! Feel free to merge, put a tag, push, etc. according to the guide.. and announce via newsbot in ansible-social at the end:)

**Comment by mariolenz** [comment]
@csmart It looks like this isn't really released yet, that is it isn't on galaxy. I think you have to add a tag for this to happen.

**Comment by csmart** [comment]
@mariolenz thanks yep, been busy so just getting back to the tagging and release now.. should be done shortly :crossed_fingers:

**Comment by csmart** [comment]
@mariolenz release `1.2.0` is up on Galaxy now :+1:

**Pull request merged**
