### PR TITLE
Fix sanity, remove EOL test targets

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fix sanity, remove EOL test targets

### CODE REVIEW

**Comment by Andersson007** [comment]
ready for review

**Comment by Andersson007** [comment]
@Im0 hi, could you please take a look? In particular, at plugins/modules/rabbitmq_publish.py. I'm removing the import detected as unused by sanity checks (so they are failing otherwise).
If it's really needed, we could put it back and add another line in ignore-2.15.txt.

**Comment by Andersson007** [comment]
@Im0 have you had a chance to take a look? if there are any concerns about the imports, we can leave them as is and add entries to ignore.txt to ignore this when passing sanity checks.
Ideas?
(fyi, i'll be on PTO next week, feel free to push to my PR and merge)

**Review by Im0 — APPROVED** [review]

**Comment by Andersson007** [comment]
@Im0 thanks for reviewing!

**Pull request merged**
