### PR TITLE
AZP: update matrix

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
AZP: update matrix

### CODE REVIEW

**Comment by Andersson007** [comment]
@csmart those integration tests failures are not related, so it's ready for review. I asked for your opinion on them in another PR

**Comment by csmart** [comment]
Looks good to me and yeah, the errors look to be from being unable to contact a specific mirror.. I'd probably like to re-run the tests, but let's merge this and see how we go.

**Comment by Andersson007** [comment]
@csmart thanks for reviewing and merging!

**Comment by csmart** [comment]
Thanks for the patch!

**Pull request merged**
